### ISSUE TITLE
Saving as psd

### ISSUE THREAD

**Issue by kwketh** [layervault/psd.rb#88]
Hi all.

Is saving/exporting back to .psd format supported by any chance? If not, does anybody know what would be required?

I have a scenario where I am loading a psd, applying changes to the tree (i.e. changing layer names) and want to export it back. If anybody could help, I would be grateful. I could not find anything about this neither in the documentation, code, provided examples or anywhere in the issues.

Other than that, this is an awesome project.

Many thanks,
kwketh

**Comment by meltingice** [comment]
Writing out modified PSDs is not supported at this time, but is something I've been considering for awhile. There used to be rudimentary support for it, but it was removed due to bugginess and overall poor code.

**Comment by kwketh** [comment]
Hi meltingice,

Thanks for coming back to me. 

Do you think you could point me to a commit hash where it used to be roughly supported? I would be really happy to have a look at how it was done, even if rudimentary. I have checked hundreds of psd-format-related projects and none of them support this. The closest I could get to using gimp CLI that can create layers but it doesn't support managing slices. Do you perhaps know any alternatives or projects that can write psd format?

On another note, I am sure you have dived into Photoshop format much more than I did and your input would be really helpful. My only requirement would be to modify slice names. It definitely doesn't seem "intuitive" in a primitive way as just modifying strings in .psd binary as no slice names come up as strings, and binwalk doesn't find any compressions in the .psd format. Do you know any articles or clear documentation that explains how Photoshop encodes slices and/or the strings? Every documentation that I found only refers to layers and not the slices. As you've developed this project, did you follow any specifications? It seems rather difficult to follow .psd format from code in general. Specification would be definitely much easier to follow, i.e. to explain what 'nodes' are in the format, etc.

Thanks a lot and my apologises for many questions.

**Comment by meltingice** [comment]
Unfortunately the feature to write out changes was removed years ago, so you're going to have to go back pretty far to find the code. I think if you go back to commits from 2013, you'll be able to find it. There is [one project](https://github.com/bengotow/PSDWriter/blob/master/Library/Shared/PSDWriter.m#L165-L470) that comes to mind that can generate PSDs, but it's written in Obj-C and I think can only generate new PSDs, not modify existing ones. Probably not what you're looking for.

Regarding modifying slice names...

Slices are in the _resources_ section of the PSD, which occurs after the header and before the layer data. Unfortunately, slices are a little messy. Depending on your version of Photoshop, they can be defined in one of two ways.

[The first way](https://github.com/layervault/psd.rb/blob/master/lib/psd/resources/slices.rb#L34-L81), which is from older versions, is that the data is stored in a static structure that's read the same way every time. Here, the slice names are stored as [unicode strings](https://github.com/layervault/psd.rb/blob/master/lib/psd/file.rb#L82-L89) (UTF16-BE), which is probably why a simple grep of the binary did not show the slice names.

[The latest way](https://github.com/layervault/psd.rb/blob/master/lib/psd/resources/slices.rb#L17-L19) stores the slice data in a _descriptor_. [Descriptors](https://github.com/layervault/psd.rb/blob/master/lib/psd/descriptor.rb) are dynamic data structures that can store a wide variety of data. In order to make data access more consistent and remove this burden of knowledge from the user, we actually [normalize the slice data](https://github.com/layervault/psd.rb/blob/master/lib/psd/resources/slices.rb#L83-L130) between the old and the new versions. Looking at this code, you can see how the data is stored in a more structured manner. Now... this means that modifying the slice name is even more complicated, because you'll need to be able to overwrite part of the descriptor in such a way that you don't break the document.

Adobe [publishes part of the PSD file spec](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/), although I have found it to be inaccurate in a couple of places. For the most part, it's an okay guide. There is also a C-based project called [libpsd](https://github.com/alco/psdump/tree/master/libpsd-0.9) that has a wealth of good information about parsing PSDs. It really helped me get PSD.rb off the ground and helped me with some of the tricker parts.

Hope that helps!

**Comment by kwketh** [comment]
Thank you meltingice.

That helps a lot :-) Even though I already had a look at the Obj-C project before, it may actually be what I need. You are also completely right about UTF16 encoding, `strings --encoding=b file.psd` perfectly lists the layer and slice names, which is what I also needed.

That all being said, I had a look at the `psd-engindata` project, is it only a parser for the Photoshop descriptors? If it could also write descriptors from the markdown, wouldn't it be exactly what I need if I understand this right?

Thanks.

**Comment by meltingice** [comment]
So the `psd-enginedata` project is actually for parsing the markup format that is used to store all of the data about text layers. The code that reads and parses descriptors is [here](https://github.com/layervault/psd.rb/blob/master/lib/psd/descriptor.rb).
